// Mocks generated by Mockito 5.2.0 from annotations
// in clean_architecture_flutter/test/screens/change_password/presentation/blocs/change_password/change_password_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:clean_architecture_flutter/core/error/failures.dart' as _i6;
import 'package:clean_architecture_flutter/screens/change_password/domain/repositories/change_password_repository.dart'
    as _i2;
import 'package:clean_architecture_flutter/screens/change_password/domain/usecases/change_password.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeChangePasswordRepository_0 extends _i1.Fake
    implements _i2.ChangePasswordRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [ChangePassword].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePassword extends _i1.Mock implements _i4.ChangePassword {
  MockChangePassword() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChangePasswordRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue: _FakeChangePasswordRepository_0())
          as _i2.ChangePasswordRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(
          _i4.ChangePasswordParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, bool>>.value(
                  _FakeEither_1<_i6.Failure, bool>()))
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}
